name: supadart
description: Generate Dart classes from your Supabase schema.
version: 1.3.8

repository: https://github.com/mmvergara/supadart
homepage: https://github.com/mmvergara/supadart
issue_tracker: https://github.com/mmvergara/supadart/issues
documentation: https://github.com/mmvergara/supadart
topics: [cli, generator, supabase, schema, class]

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.2.1
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  intl: ^0.19.0
  lints: ^3.0.0
  supabase: ^2.2.7
  test: ^1.24.0

executables:
  supadart:

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
